// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koqvynbgfeffkbpxzauv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcXZ5bmJnZmVmZmticHh6YXV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTUyNzEsImV4cCI6MjA3MjEzMTI3MX0.vjr76xE-afu1Dcyo-CLqSpj9NP28quoq5cMWZWCbfFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});